server:
  port: 0
spring:
  application:
    name: 'cliente'
  config:
    import: "optional:configserver:http://localhost:8888"
 
---
#spring:
 # application:
   # name: 'cliente'
 # config:
 #   import: "optional:configserver:http://config-server:8888"
  #profiles:
  #  active: docker